repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: [ --no-ensure-ascii, --autofix ]
      - id: check-added-large-files
      - id: debug-statements
      - id: requirements-txt-fixer
        language_version: python3

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.1
    hooks:
      - id: reorder-python-imports
        args: [ --py37-plus ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
      - id: pyupgrade
        args: [ --py37-plus ]
